name: Build

on:
  push:
    tags:
      - "*"
      - "!**-alpha**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v1



      - name: Generate Changelog
        run: ./changelog.sh

      - name: Package and Release
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{secrets.GITHUB_TOKEN}}
