name: Build

on:
  push:
    branches:
      - master
    tags:
      - "*"
      - "!**-alpha**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          files: 'BlizzHUDTweaks/Source'
          config: 'https://github.com/PhenomDevel/BlizzHUDTweaks/blob/master/.luacheckrc'
          args: "--no-color -q"
          annotate: warning

      - name: Generate Changelog
        run: ./changelog.sh

      - name: Package and Release
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
