name: Build Github

on:
  push:
    tags:
      - "*"
      - "**-beta**"
      - "!**-alpha**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Generate Changelog
        run: ./changelog.sh

      - name: Read CHANGELOG.md
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CHANGELOG.md

      - name: Create Github Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.content }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}